import type { NextPage } from "next";

import { useSession, signIn, signOut } from "next-auth/react";

import Head from "next/head";
import { useEffect, useState } from "react";
import Avatar from "../components/Register.tsx/Avatar";
import Register from "../components/Register.tsx/Register";

interface UserInterface {
  name: string;
  image: string;
  email: string;
}

const Home: NextPage = () => {
  const [user, setUser] = useState<UserInterface>();
  const { data: session } = useSession();

  const renderCurrentUser = () => {
    if (session) {
      return <p>{JSON.stringify(session)}</p>;
    }
  };

  const renderLogin = () => {
    if (session) {
      console.log(session);
      return (
        <main className="w-full h-screen flex justify-center items-center">
          <Register login={false} />
        </main>
      );
    }

    return (
      <main className="w-full h-screen flex justify-center items-center">
        <Register />
      </main>
    );
  };

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {renderCurrentUser()}
      {renderLogin()}
    </div>
  );
};

export default Home;
