import type { NextPage } from "next";

import { useSession, signIn, signOut } from "next-auth/react";

import Head from "next/head";
import Register from "../components/Register.tsx/Register";

const Home: NextPage = () => {
  const { data: session } = useSession();

  const renderLogin = () => {
    if (session) {
      console.log(session);
      return (
        <main>
          <Register login={false} />
        </main>
      );
    }

    return (
      <main className="w-full h-screen flex justify-center items-center">
        <Register />
      </main>
    );
  };

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {renderLogin()}
    </div>
  );
};

export default Home;
